Mvc/FluentJqGrid.Mvc4.Demo/Controllers/SimpleLoadController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AdventureWorksLT.Data.Data;
using AdventureWorksLT.Data.Infrastructure;
using FluentJqGrid.Mvc4.Demo.Common;
using FluentJqGrid.Mvc4.Demo.Infrastructure;
using FluentJqGrid.Mvc4.Demo.SampleSources;
using FluentJqGrid.Settings;

namespace FluentJqGrid.Mvc4.Demo.Controllers
{
    public class SimpleLoadController : Controller
    {
        private readonly SrcSamples _srcSamples;
        private readonly IRepository<Product> _productRepository;

        public SimpleLoadController(SrcSamples srcSamples, IRepository<Product> productRepository)
        {
            _srcSamples = srcSamples;
            _productRepository = productRepository;
        }

        public ActionResult JsonLoad()
        {
            ViewData["src"] = _srcSamples.SetSamples(SimpleLoad.JsonLoad_View, SimpleLoad.JsonLoad_Controller,
                                                     SimpleLoad.JsonLoad_Description);
            return View();
        }

        public ActionResult JsonLoadAjaxPost(JqGridPost post)
        {
            var product = new PagedList<Product>(
                    _productRepository.Table.OrderBy(m => m.ProductID), post.page, post.rows);

            var jqRows = product.Select(item => new GridRow
            {
                Id = item.ProductID.ToString(),
                Cell = { item.ProductID, item.Name, item.Size, item.ProductCategory.Name, item.ListPrice }
            }).ToList();
            var json = product.ToJqGridData(post.page, jqRows);
            return Json(json.ToData(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult StronglyTypedColumns()
        {
            ViewData["src"] = _srcSamples.SetSamples(SimpleLoad.StronglyTypedColumns_View, SimpleLoad.StronglyTypedColumns_Controller,
                                                     SimpleLoad.StronglyTypedColumns_Description);

            return View(new Models.ProductModel());
        }

        public ActionResult StronglyTypedColumnsAjaxPost(JqGridPost post)
        {
            var products = new PagedList<Product>(
                    _productRepository.Table.OrderBy(m => m.ProductID), post.page, post.rows);

            var jqRows = products.Select(item => new GridRow
            {
                Id = item.ProductID.ToString(),
                Cell = { item.ProductID, item.Name, item.Size, item.ProductCategory.Name, item.ListPrice }
            }).ToList();
            var json = products.ToJqGridData(post.page, jqRows);
            return Json(json.ToData(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult XmlLoad()
        {
            ViewData["src"] = _srcSamples.SetSamples(SimpleLoad.XmlLoad_View, SimpleLoad.XmlLoad_Controller,
                                                     SimpleLoad.XmlLoad_Description);
            return View();
        }

        public ActionResult XmlLoadAjaxPost(JqGridPost post)
        {
            var products = new PagedList<Product>(
                    _productRepository.Table.OrderBy(m => m.ProductID), post.page, post.rows);

            var jqRows = products.Select(item => new GridRow
            {
                Id = item.ProductID.ToString(),
                Cell = { item.ProductID, item.Name, item.Size, item.ProductCategory.Name, item.ListPrice }
            }).ToList();
            var json = products.ToJqGridData(post.page, jqRows);
            return Content(json.ToData().ToXml(), "text/xml");
        }

        public ActionResult ColumnSettingLoad()
        {
            ViewData["src"] = _srcSamples.SetSamples(string.Empty, string.Empty,
                                                     string.Empty);
            var columns = new[]
                {
                    new JqGridColumnSettings
                    {
                        Name = "ProductID",
                        Header ="Id"
                    },
                    new JqGridColumnSettings
                    {
                        Name = "Name",
                        Header ="Name",
                        EditSettings = new EditSettings
                            {
                                EditType = EditType.TextArea,
                                Cols = 10,
                                Rows = 2
                            },
                        Align = ColumnAlign.Right
                    },
                    new JqGridColumnSettings
                    {
                        Name = "Size",
                        Header ="Size"
                    },
                };
            ViewData["ProductColumns"] = columns;
            return View();
        }

        public ActionResult ColumnSettingLoadAjaxPost(JqGridPost post)
        {
            var products = new PagedList<Product>(
                    _productRepository.Table.OrderBy(m => m.ProductID), post.page, post.rows);

            var jqRows = products.Select(item => new GridRow
            {
                Id = item.ProductID.ToString(),
                Cell = { item.ProductID, item.Name, item.Size} //, item.ProductCategory.Name, item.ListPrice }
            }).ToList();
            var json = products.ToJqGridData(post.page, jqRows);
            return Json(json.ToData(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult LoadOnce()
        {
            ViewData["src"] = _srcSamples.SetSamples(string.Empty, string.Empty,
                                                     string.Empty);
            return View(new Models.ProductModel());
        }

        public ActionResult LoadOnceAjaxPost(JqGridPost post)
        {
            var products = _productRepository.Table.OrderBy(m => m.ProductID);
            var jqRows = products.ToList().Select(item => new GridRow
            {
                Id = item.ProductID.ToString(),
                Cell = { item.ProductID, item.Name, item.Size, item.ProductCategory.Name, item.ListPrice }
            }).ToList();

            var json = products.ToJqGridData(post.page, post.rows, jqRows);
            return Json(json.ToData(), JsonRequestBehavior.AllowGet);
        }
    }
}

Mvc/FluentJqGrid.Mvc4.Demo/Views/Shared/SimpleVerticalMenu.cshtml
@model IList<FluentJqGrid.Mvc4.Demo.Models.SimpleVerticalMenuModel>
<div class="vmenu">
    @foreach (var menuItem in Model)
    {
        <div class="vmenu-section">@menuItem.Text</div>
        
        <div class="@(menuItem.Active ? "active" : "inactive")">
            <ul class="vmenu-list">
                @foreach (var item in menuItem.MenuItems)
                {
                    <li>@Html.ActionLink(item.Text, item.Action, item.Controller, null, new { @class = item.Selected ? "selected" : "unselected" })</li>
                }
            </ul>
        </div>
    }
</div>

Mvc/FluentJqGrid.Mvc4.Demo/Views/Shared/_AppLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>FluentJqGrid Demo: @ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css", 
                   "~/Content/themes/base/uiall", 
                   "~/Scripts/css/jqgrid", 
                   "~/Content/themes/jqgradientca/gca",
                   "~/Content/shcss")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/Scripts/jquery", 
                    "~/Scripts/jqueryui", 
                    "~/Scripts/jqgrid", 
                    "~/Scripts/shjs", 
                    "~/Scripts/jqplugins")
    @RenderSection("scripts", required: false)
    
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30285050-1']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
</head>
<body>
    <header id="header">
        <div id="header-wrapper">
            <div id="title">
                <h1>FluentJqGrid</h1>
                <h6>JqGrid Helper for Asp.Net Mvc</h6>
            </div>
        </div>

    </header>
    <div id="wrapper">
        <div id="nav">
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Download", "Index", "Home")</li>
                    <li>@Html.ActionLink("Demo", "JsonLoad", "SimpleLoad")</li>
                    <li>@Html.ActionLink("Documentation", "Index", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
            <br />
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

Mvc/FluentJqGrid.Mvc4.Demo/Views/Shared/_OneColumn.cshtml
@{
    Layout = "_AppLayout.cshtml";
}
<div id="middle">
    @RenderBody()
</div>

Mvc/FluentJqGrid.Mvc4.Demo/Views/Shared/_SrcSamples.cshtml
@model FluentJqGrid.Mvc4.Demo.Common.SrcSamples
@using FluentJqGrid.Mvc4.Demo.Common
@{
    var sources = @ViewData["src"] as SrcSamples;
    string controllerSrc = (sources != null) ? sources.ControllerSrc : string.Empty;
    string viewSrc = (sources != null) ? sources.ViewSrc : string.Empty;
    string description = (sources != null) ? sources.Description : string.Empty;
}
<script type='text/javascript'>
    $(function () {
        $("#src-container").organicTabs({
            "speed": 200
        });
    });
</script>
<h2>Sample Sources</h2>
<div id="src-container">
    <ul class="nav">
        <li class="nav-one"><a href="#view" class="current">View</a></li>
        <li class="nav-two"><a href="#controller">Controller</a></li>
        <li class="nav-three"><a href="#description">Description</a></li>
    </ul>
    <div class="list-wrap">
        <ul id="view">
            <li>
                <pre class="brush: csharp">@(viewSrc)</pre>
            </li>
        </ul>
        <ul id="controller" class="hide">
            <li>
                <pre class="brush: csharp">@(controllerSrc)</pre>
            </li>
        </ul>
        <ul id="description" class="hide">
            <li>
                <pre class="brush: csharp">@(description)</pre>
            </li>
        </ul>
    </div>
</div>

Mvc/FluentJqGrid.Mvc4.Demo/Views/Shared/_TwoColumn.cshtml
@{
    Layout = "_AppLayout.cshtml";
}
@section scripts{
    
}
<div id="sidebar">
    @{ Html.RenderAction("SimpleVerticalMenu", "Home"); }
</div>
<div id="container">
    <div style="margin: 10px;">
        @RenderBody()
    </div>
</div>
@RenderSection("scripts1", required: false)
<script type="text/javascript">
    $(function () {
        //$('#container').css("min-height", $('#main').height());
        SyntaxHighlighter.all();
    });
</script>